version: '3.4'

services:
  gosu:
    image: kapdap/gosu:${GOSU_VERSION:-latest}
    build:
      context: .
      args:
        GOSU_VERSION: ${GOSU_VERSION:-1.10}
        GOSU_ARCHITECTURES: ${GOSU_ARCHITECTURES:-amd64 aarch64 amdhf}
        GOSU_KEY: ${GOSU_KEY:-0x036A9C25BF357DD4}
