version: '3.4'

services:
  gosu:
    image: kapdap/gosu:${GOSU_VERSION:-latest}
    build:
      context: .
      args:
        GOSU_VERSION: ${GOSU_VERSION}
        GOSU_ARCHITECTURES: ${GOSU_ARCHITECTURES}
    environment:
      DEBUG: 'true'
      GPG_KEYS: ${GPG_KEYS}
